# Generated by Django 3.2 on 2025-01-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0003_auto_20250105_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
